/*
 * This source file was generated by the Gradle 'init' task
 */
package school21.AP1JvT03;

public class App {
    public String getGreeting() {
        return "Hello WorldTTTTTTTTTT!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
