/*
 * This source file was generated by the Gradle 'init' task
 */
package school21.AP1JvT03;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
